config/routes.rb
Rails.application.routes.draw do

    ActiveAdmin.routes(self)
    get 'pages/index'
    get 'pages/about'

    devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    scope '(:locale)', locale: /fr|en/ do  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

        root to: 'pages#index'
        resources :users, only: [:show, :edit, :update] # User Profile page, the rest is handeld by Devise

        get 'change_language/:language' => 'application_controller#change_language', as: 'change_language'

        resources :shops do
          get 'promotions', to: 'shops#promotions'
          put 'activation', to: 'shops#changestatus'
        end

        resources :promotions do
         post 'add_to_order', to: 'add_to_order#promotions', on: :member
         post 'filtered', to: 'promotions#index'
        end

        resources :orders do
         post 'confirm', on: :member
        end

    end
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :promotions
  geocoded_by :full_address
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  after_validation :geocode

  after_create :send_confirmation_email

  def full_address
    "#{address}, #{street_number} #{zip_code} #{city} #{country}"
  end

  private

  def send_confirmation_email
    ShopMailer.partnership_demand(self).deliver_now
  end
end

app/controllers/shops/promotions_controller.rb
class Shops::PromotionsController < ApplicationController
  # before_action :set_promotion, only: [:show, :edit, :update, :destroy]
  layout 'user'
  def index
    @promotions = Promotion.joins(:shop).where("shops.user_id = ?", current_user.id)
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy, :changestatus]
  before_action :authenticate_user!, only: [:create, :new, :update, :destroy, :edit, :changestatus]

# Flash notification when trying an action for which the user is not authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = t('flash.authorization')
    redirect_to(root_path)
  end

### PUBLIC METHODS ###
  def index
      @params_search = false
    if params[:address]
      @params_search = true
      @address = params[:address]
      @shops = Shop.near(@address, 10)
    else
      @shops = Shop.where.not(latitude: nil, longitude: nil)# Why not showing all shops?

    end
    @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
    end
  end

  def show
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
    end
  end

### RESTRICTED METHODS ###

  def promotions # promotions admin page for shop level user / not a public index !
    @shop = Shop.find(params[:shop_id])
    authorize @shop # Only the user who owns the shop is authorized
    @promotions = Promotion.where("shop_id = ?", @shop.id)
    @hash = Gmaps4rails.build_markers(@promotions) do |promo, marker|
        marker.lat promo.shop.latitude
        marker.lng promo.shop.longitude
    end
    @promotions_active = []
    @promotions.map do |prom|
      if (prom.promotion_status == true && prom.validity > Time.now)
        @promotions_active << prom unless prom.nil?
      end
    end
     @promotions_inactive = []
     @promotions.each do |prom|
       if (prom.promotion_status == false || prom.validity < Time.now)
          @promotions_inactive << prom unless prom.nil?
       end
     end
  end

  def new
    authorize current_user
    @shop = Shop.new()
  end

  def create
    authorize current_user
    if current_user
      @shop = Shop.new(shop_params)
      @shop.user_id = current_user.id
      @shop.save
    else
      @shop = Shop.new(shop_params)
      session[:shop] = shop_params
      @shop.save
    end
  flash[:notice] = t('partner.flash')
  redirect_to promotions_path
  end

  def changestatus # Activate or de-activate a promo
    promo = Promotion.find(params[:promo_id])
    authorize promo # Only the user who owns the shop owning the promo is authorized
    promo.change_status
    promo.save!
    redirect_to shop_promotions_path(@shop)
  end


  def edit
    authorize @shop # Only the user who owns the shop is authorized
  end

  def update
    authorize @shop # Only the user who owns the shop is authorized
    @shop.update(shop_params)
    redirect_to promotions_path
  end

  def destroy
    authorize @shop # Only the user who owns the shop is authorized
    @shop.destroy
  end

  private
    def shop_params
      params.require(:shop).permit(:name_of_the_store, :category, :description, :phone_number, :VAT_number, :address, :zip_code, :city, :country)
    end

    def set_shop
      @shop = Shop.find(params[:id])
    end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div class="container top">
<div class="row">

<div class="container padded-top">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(shop) do |s| %>
      <div class="form-inputs">
        <%= s.input :name_of_the_store %>
        <%= s.input :address %>
        <%= s.input :zip_code %>
        <%= s.input :city %>
        <%= s.input :country, priority: [ 'FR' ] %>
        <%= s.input :category %>
        <%= s.input :description %>
        <%= s.input :phone_number %>
        </div>
        <%= s.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>"></script>
<% end %>
</div>
</div>

app/views/shops/edit.html.erb
<h1>Shops#edit</h1>
<p>Find me in app/views/shops/edit.html.erb</p>

app/views/shops/index.html.erb
<div class="banner" style="background: url('http://res.cloudinary.com/desy3o0oh/image/upload/c_scale,w_1000/v1483364194/shop-cover_kg8clo.jpg'); background-size: cover !important;">
 <div class="banner-content">
  <h1><%= t('shop.index-1') %><span class="green"><%= t('shop.index-2') %></span></h1>
 </div>

 <div class="homepage-search">
  <form action="" method="get" class="form-inline">
   <div class="form-group">
     <input type="text" id="current_location" name="address" class="form-control" placeholder=<%="#{t('shop.location')}"%> aria-describedby="sizing-addon1">
   </div>
    <button type="submit" id="localisation" class="btn btn-form"><%= t('shop.bouton') %></button>
  </form>
 </div>
</div>


<div class="container bottom">
 <% if @params_search %>
   <h3 class="text-center bottom"><span class="green"><strong> <%= @shops.uniq.length  %></strong></span> <%=t('shop.nearby', count: @shops.uniq.length)%> <span class="green"></h3>
 <% else %>
  <h3 class="text-center bottom"><span class="green"><strong> <%= @shops.count %></strong></span> <%=t('shop.partner', count: @shops.count)%><span class="green"></h3>
 <% end %>

 <div class="row">
 <% if @shops.any? %>
   <% @shops.each_with_index do |shop, index| %>
     <div class ="col-xs-12 col-md-4">
       <p class="promo-validity text-center"> <%= shop.name_of_the_store %></p>
       <%= link_to shop_path(shop) do %>
       <div class="thumbnail">
          <div class="thumbnail-img">
         <%= cl_image_tag(shop.user.facebook_picture_url,:height=>210, :width=>340,crop: :fill) unless shop.user.facebook_picture_url.nil?%>
          </div>
         <div class="caption">
           <h5><strong><i class="fa fa-map-marker fa-lg" aria-hidden="true"> </i> <%= shop.street_number %> <%= shop.address %> <%= shop.zip_code %> <%= shop.city %></strong></h5>
           <p class="promo-title"><%= shop.category %></p>
         </div>
       </div>
       <%end%>
     </div>
     <% if index.odd?%>
     <% end %>
   <% end %>
   <% else %>
     <h2 class="text-center bottom"><%= t('shop.no-partner') %></h2>
   <% end %>
   </div>
</div>

app/views/shops/new.html.erb
<div class="banner" style="background: url('http://res.cloudinary.com/desy3o0oh/image/upload/c_scale,w_1000/v1483364193/shop_ukbfgm.jpg'); background-size: cover !important;">
  <div class="banner-content">
    <h1><%= t('partner.become') %></h1>
    <p><%= t('partner.slogan') %></p>
  </div>
</div>

<div class="container text-center padded features">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <img src="http://img.freepik.com/free-icon/recycle-bin-interface-symbol_318-56523.jpg?size=338&amp;ext=jpg" width="103" height="93" alt="">
      <h2><%=t('partner.reduce')%></h2>
      <p><%=t('partner.sell')%></p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <img src="http://www.tesradio.com/resources/client%20icon.png" width="103" height="93" alt="">
      <h2><%=t('partner.attract')%></h2>
      <p><%=t('partner.visibility')%></p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <img src="https://image.freepik.com/free-icon/euro-banknotes-stack_318-56433.jpg" width="103" height="93" alt="">
      <h2><%=t('partner.increase')%></h2>
      <p><%=t('partner.with')%></p>
    </div>
  </div>
</div>

<div class="text-center padded" id="newsletter">
  <h2><%=t('partner.partner')%></h2>
  <p><%=t('partner.notice')%></p>
  <%= render 'form', shop: @shop %>
</div>

app/views/shops/promotions.html.erb
<div class="container top">
<%= link_to '', promotions_path, { :class=>"btn-minim fa fa-arrow-left" } %>
 <div class="row">
  <h2 class="text-center bottom"><%= t('shop.promo-active') %></h2>
 <% unless @promotions_active.empty? %>
   <% @promotions_active.each_with_index do |promo, index| %>
     <div class ="col-xs-12 col-md-4">
       <p class="promo-validity text-center"> <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i> <%= distance_of_time_in_words(promo.validity - Time.now) %></p>
       <p class="text-center"><%= t('shop.digicode') %><strong><%= promo.digits_code %></strong></p>
       <%= link_to promotion_path(promo) do %>
       <div class="thumbnail">
         <div class="thumbnail-img">
         <%= cl_image_tag(promo.photo_url,:height=>210, :width=>340,crop: :fill) unless promo.photo_url.nil?%>
          </div>
         <div class="caption">
           <h5><strong><%= promo.description%></strong></h5>
           <p class="promo-discount">- <%= ((1-(promo.price_after_promotion_per_unit.to_f/promo.initial_price_per_unit.to_f))*100).round %> %</p>
           <p class="promo-price"><%= promo.price_after_promotion_per_unit %>€</p>
            <%= link_to '' ,shop_activation_path( promo_id: promo.id, id: params["shop_id"].to_i), method: :put, :class=>"btn-minim fa fa-times fa-lg pull-left"  %>
         </div>
       </div>
       <%end%>
     </div>
     <% if index.odd?%>
     <!--<div class="clearfix"></div>-->
     <% end %>
   <% end %>
   <% else %>
     <p class="text-center bottom"><%= t('shop.no-promo') %></p>
   <% end %>
   </div>

  <div class="row">
  <h2 class="text-center bottom"><%= t('shop.activation') %></h2>
 <% unless @promotions_inactive.empty? %>
   <% @promotions_inactive.each_with_index do |promo, index| %>
     <div class="col-xs-12 col-md-4">
       <p class="promo-validity inactive text-center"> <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i> <%= distance_of_time_in_words(promo.validity - Time.now) %></p>
       <%= link_to promotion_path(promo) do %>
       <div class="thumbnail">
          <div class="thumbnail-img">
         <%= cl_image_tag(promo.photo_url,:height=>210, :width=>340,crop: :fill) unless promo.photo_url.nil?%>
          </div>
         <div class="caption">
           <h5><strong><%= promo.description%></strong></h5>
           <p class="promo-discount">- <%= ((1-(promo.price_after_promotion_per_unit.to_f/promo.initial_price_per_unit.to_f))*100).round %> %</p>
           <p class="promo-price"><%= promo.price_after_promotion_per_unit %>€</p>


           <%= link_to '', edit_promotion_path(promo.id),  :class=>"btn-minim fa fa-pencil-square-o fa-lg pull-left"  %>
           <%= link_to '',shop_activation_path( promo_id: promo.id, id: params["shop_id"].to_i), method: :put, :class=>"btn-minim fa fa-check fa-lg pull-left"  %>

         </div>
       </div>
       <%end%>
     </div>
     <% if index.odd?%>

     <% end %>
   <% end %>
   <% else %>
   <% end %>
    <%= link_to new_promotion_path(shop_id: params[:shop_id]), class: 'btn btn-lg btn-default btn-upload' do %>
      <i class="fa fa-lg fa-cloud-upload"></i>
      <br>
      <%= t('shop.upload') %>
    <% end %>
  </div>

</div>

app/views/shops/show.html.erb
<div class="container top">
  <%= link_to '',shops_path, { :class=>"btn-minim fa fa-arrow-left" } %>
</div>
  <div class="row top">
    <div class="col-md-4 col-md-offset-4">
      <div class="banner-seller ">

        <%#= Link_to ' Subtract',  order_path(promotion_id: @promotion.id, quantity_ordered: -1), method: :put %>
        <%#= Link_to ' Add',  order_path(promotion_id: @promotion.id, quantity_ordered: 1), method: :put %>
       <div class="profil-seller text-center">
          <div class="avatar-large">
        <%= cl_image_tag @shop.user.facebook_picture_url unless @shop.user.facebook_picture_url.nil?%></div><h4><strong><%= @shop.name_of_the_store %></strong></h4>
        <%= @shop.category %>
        <p class="text-center top"><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i> <%= @shop.full_address  %></p>
        <p class="text-center top"><i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <%= @shop.phone_number  %></p>
        <p class="text-center top"><i > <%= @shop.description  %></i></p>
      </div>
      </div>
    </div>
  <div id="map" class="col-md-6 bottom" style="width: 100%; height: 300px;">

        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function() {
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
            });
          <% end %>
        <% end %>
  </div>

  </div>