config/routes.rb
Rails.application.routes.draw do

    ActiveAdmin.routes(self)
    get 'pages/index'
    get 'pages/about'

    devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    scope '(:locale)', locale: /fr|en/ do  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

        root to: 'pages#index'
        resources :users, only: [:show, :edit, :update] # User Profile page, the rest is handeld by Devise

        get 'change_language/:language' => 'application_controller#change_language', as: 'change_language'

        resources :shops do
          get 'promotions', to: 'shops#promotions'
          put 'activation', to: 'shops#changestatus'
        end

        resources :promotions do
         post 'add_to_order', to: 'add_to_order#promotions', on: :member
         post 'filtered', to: 'promotions#index'
        end

        resources :orders do
         post 'confirm', on: :member
        end

    end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible animated fadeIn" role="alert">
    <button type="button slideUp" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible animated fadeIn" role="alert">
    <button type="button slideUp" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>

<% end %>

app/views/shared/_footer.html.erb
<footer>
<div class="container">
<div class="row">
<div class="col-xs-12 col-md-4">
<strong><p>Contact</p></strong>
<p><%= t('footer.contact') %></p>
</div>
<div class="col-xs-12 col-md-4">
<strong><p><%= t('footer.about') %></p></strong>
<p><%= t('footer.description') %></p>
</div>
<div class="col-xs-12 col-md-4">
<strong><p><%= t('footer.follow') %></p></strong>
<ul>
 <li><a href=""><i class="fa fa-youtube"></i></a></li>
 <li><a href=""><i class="fa fa-instagram"></i></a></li>
 <li><a href=""><i class="fa fa-facebook"></i></a></li>
 <li><a href=""><i class="fa fa-twitter"></i></a></li>
</ul>
</div>
</div>
</div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar-default navbar-fixed-top">
  <div class="container-fluid">

      <%= link_to root_path, class: "navbar-brand navbar-left" do %>
          Robin Food
      <% end %>

    <div class="navbar-right">
    <% if user_signed_in? %>

    <!-- Different navigation if login or not-->

     <!-- Profile picture and dropdown -->
     <div class="dropdown pull-right">
       <% avatar_url = current_user.facebook_picture_url || "https://image.freepik.com/free-icon/user-male-shape-in-a-circle-ios-7-interface-symbol_318-35357.jpg" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-haspopup" => true, "aria-expanded" => false %>
        <ul class="dropdown-menu">
          <% unless current_user.shops.empty? %>
            <li>
              <%= link_to shop_promotions_path(current_user.shops.first.id) do %>
              <i class="fa fa-sign-out"></i>  Manage My Products
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
     </div>
    </div>
    <% else %>
    <div class="pull-right">
    <!-- Login link-->
    <%= link_to new_user_session_path do %>
    <i class="fa fa-user"></i> <%= t(".sign_in", default: "Login")%>
    <% end %>
    <!-- Sign Up link (call-to-action) -->
    <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, {class: "sign btn btn-form hidden-xs"} %>
    </div>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to root_path, class: "navbar-brand" do %>
          Robin <span>Food</span>
      <% end %>
    </div>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to pages_about_path, class: '.profile' do %>
              <%= t('navigation.about') %>
            <% end %>
          </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to orders_path, class: '.profile' do %>
              <%= t('navigation.orders') %>
            <% end %>
          </li>
          <li>
            <% unless current_user.shops.empty? %>
              <%= link_to shop_promotions_path(current_user.shops.first.id) do %>
              <%= t('navigation.manage-products') %>
              <% end %>
            <% end %>
          </li>
          <li>
            <% if current_user.shops.empty? %>
            <%= link_to new_shop_path, class: '.profile' do %>
            <%= t('navigation.partnership') %>
              <% end %>
              <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user), class: '.profile' do %>
              <%= t('navigation.edit-account') %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'hidden-mg hidden-lg' do %>
              <%= t('navigation.sign-out') %>
          <% end %>
          </li>
          <% else %>
             <li>
            <%= link_to new_shop_path, class: '.profile' do %>
            <%= t('navigation.partnership') %>
              <% end %>
          </li>
          <li>
             <%= link_to new_user_session_path, class: 'hidden-mg hidden-lg' do %>
          <%= t(".sign_in", default: "Login")%>
        <% end %>
          </li>
          <li>
          <%= link_to new_user_registration_path, class: '.sign_up hidden-sm hidden-lg' do %>
          <%= t('navigation.sign_up') %>
        <% end %>
          </li>
          <% end %>
        <li>
          <% if I18n.locale == I18n.default_locale %>
          <%= link_to url_for( :locale => 'fr' ) , class: '.sign_up hidden-sm hidden-lg' do %>
          <%= flag_icon(:fr) %>
          <%= t('language.français') %>
            <% end %>
            <% else %>
          <%= link_to url_for( :locale => 'en' ), class: '.sign_up hidden-sm hidden-lg' do %>
          <%= flag_icon(:gb) %>
          <%= t('language.english') %>
            <% end %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="pull-right">
      <% if user_signed_in? %>
        <div class="pull-right hidden-xs ">
        <%= link_to destroy_user_session_path, method: :delete, class: '.sign up btn btn-link btn-success navbar-btn' do %>
            <%= t('navigation.sign-out') %>
          <% end %>
        </div>
          <div style="margin-right:100px" class="pull-right hidden-xs ">
            <% if I18n.locale == I18n.default_locale %>
            <%= link_to url_for( :locale => 'fr' ), class: '.sign up btn btn-link btn-success navbar-btn' do %>
            <%= flag_icon(:fr) %>
            <%= t('language.français') %>
              <% end %>

            <% else %>
            <%= link_to url_for( :locale => 'en' ), class: '.sign up btn btn-link btn-success navbar-btn' do %>
              <%= flag_icon(:gb) %>
              <%= t('language.english')%>
            <% end %>
        <% end %>
    </div>
        <div style="margin-right:220px" class="pull-right hidden-xs ">
          <% if current_user.facebook_picture_url %>
          <%= cl_image_tag current_user.facebook_picture_url, class: "avatar" %>
          <% else  %>
          <i class="fa fa-2x fa-user-circle-o"></i>
          <% end %>
        </div>

      </div>
    <% else %>

      <div style="margin-right:140px" class="pull-right hidden-xs ">
        <% if I18n.locale == I18n.default_locale %>
          <%= link_to url_for( :locale => 'fr' ), class: '.sign up btn btn-link btn-success navbar-btn' do %>
          <%= flag_icon(:fr) %>
          <%= t('language.français') %>
           <% end %>

        <% else %>
          <%= link_to url_for( :locale => 'en' ), class: '.sign up btn btn-link btn-success navbar-btn' do %>
          <%= flag_icon(:gb) %>
          <%= t('language.english')%>
          <% end %>
        <% end %>
    </div>


      <div style="margin-right:85px" class="pull-right hidden-xs ">

        <%= link_to new_user_session_path, class: 'btn btn-link navbar-btn' do %>
          <%= t(".sign_in", default: "Login")%>
        <% end %>


      </div>
      <div class="pull-right hidden-xs " style="color:rgb(148, 219, 70);">
        <%= link_to new_user_registration_path, class: '.sign up btn btn-link btn-success navbar-btn' do %>
          <%= t('navigation.sign_up') %>
        <% end %>
      </div>
       <% end %>
  </div>

</nav>