config/routes.rb
Rails.application.routes.draw do

    ActiveAdmin.routes(self)
    get 'pages/index'
    get 'pages/about'

    devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    scope '(:locale)', locale: /fr|en/ do  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

        root to: 'pages#index'
        resources :users, only: [:show, :edit, :update] # User Profile page, the rest is handeld by Devise

        get 'change_language/:language' => 'application_controller#change_language', as: 'change_language'

        resources :shops do
          get 'promotions', to: 'shops#promotions'
          put 'activation', to: 'shops#changestatus'
        end

        resources :promotions do
         post 'add_to_order', to: 'add_to_order#promotions', on: :member
         post 'filtered', to: 'promotions#index'
        end

        resources :orders do
         post 'confirm', on: :member
        end

    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :promotion
  belongs_to :user, optional: true
  validates :quantity_ordered, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :confirm, :destroy, :add_to_order]
  before_action :authenticate_user!

    def index
      unless session[:order].nil?
        @order = Order.new(session[:order])
        @order.user = current_user
        @order.status = "To be confirmed"
        @order.save!
        session[:order] = nil
      end
      @orders = current_user.orders.where(status: ["To be confirmed","Booked"]).order("updated_at DESC") #maybe better to order by status
    end

    def show
      if policy(@order).show?
        @order = Order.find(params[:id])
        @order.status = "Booked" unless @order.status == "Picked-up"
        @order.save!
        @hash = Gmaps4rails.build_markers(@order) do |order, marker|
          marker.lat order.promotion.shop.latitude
          marker.lng order.promotion.shop.longitude
        end
      end
      authorize @order
    end

    def new
      @order = Order.new
    end

    def create
      if current_user
        @order = Order.new(order_params)
        @order.user_id = current_user.id
        @order.status = "To be confirmed"
        @order.save!
        redirect_to orders_path
      else
        session[:order] = order_params
        redirect_to new_user_session_path
      end
    end


    def edit
      authorize @order
    end

    def update
      authorize @order
      @order.update!(order_params)
           redirect_to orders_path
    end

    def destroy
      authorize @order
    end

    def confirm
      authorize @order
      code =  (params[:confirm]["code"]).to_i
      if @order.promotion.digits_code == code
        @order.status = "Picked-up"
        @order.save!
        flash[:notice] = t('flash.coupon-ok')
        redirect_to order_path(@order.id)
      else
        flash[:alert] = t('flash.coupon-fail')
        redirect_to order_path(@order.id)
      end

      def booked
          @order = Order.find(params[:id])
          @order.status = "Booked"
          @order.save!
      end

    end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:promotion_id, :quantity_ordered)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="container top bottom">
  <%= link_to '', promotions_path, { :class=>"btn-minim fa fa-arrow-left" } %>
  <h1 class="text-center"><%= t('orders.myorders') %></h1>
  <% @orders.each do |order| %>
    <div class="row">

        <div class="separator"></div>
        <div class="col-md-4">
          <div class="cart-sec">
           <% if order.promotion.photo_url %>
           <%= image_tag order.promotion.photo_url, class: "img-responsive" %>
           <% end %>
         </div>
       </div>

       <div class="col-md-4">
        <div class="cart-item-info">
         <% if order.promotion.shop.photo_url %>
         <%= image_tag order.promotion.shop.photo_url, class: "avatar-large" %>
         <%= order.promotion.shop.name_of_the_store %>
         <% end %>
         <h3 class="bottom"><%= order.promotion.description %></h3>
         <p><%= t('orders.quantity') %>: <%= order.quantity_ordered %> <%= order.promotion.unit %></p>
         <p><%= t('orders.price') %>: <%= (order.promotion.price_after_promotion_per_unit * order.quantity_ordered).round(2) %> €</p>
         <p>Status: <% if order.status == "To be confirmed" %>
                    <%= t('orders.status.tbc') %>
                    <% elsif order.status == "Booked" %>
                    <%= t('orders.status.booked') %>
                    <% else %>
                    <%= t('orders.status.picked-up') %>
          <%end%></p>
       </div>
       </div>

       <div class="col-md-4">
        <% if order.status != "Picked-up" && order.status != "Booked" %>
        <div class="cart-edit text-center">
          <%= link_to promotion_path(order.promotion), class: 'btn-medium-confirm' do %>
            <i class="fa fa-lg fa-pencil-square-o"></i>
            <%= t('orders.edit') %>
          <% end %>
        </div>

        <div class="cart-confirm text-center">
          <%= link_to order_path(order), class: "btn-medium-confirm" do %>
            <i class="fa fa-check"></i>
            <%= t('orders.confirm') %>
          <% end %>
        </div>

        <% else order.status == "Booked" %>
          <div class="cart-confirm text-center">
            <%= link_to order_path(order), class: 'btn-medium-confirm' do %>
              <i class="fa fa-check"></i>
              <%= t('orders.generate') %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
 </div>
</div>
 </div>
</div>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<div class="container top">
<%= link_to '',orders_path, { :class=>"btn-minim fa fa-arrow-left" } %>
</div>
<div class="row top">
      <% if @order.status == "Booked" %>
        <h1 class="text-center bottom"><%= t('orders.thanks') %><%= @order.promotion.shop.name_of_the_store%> <%= t('orders.pick-up') %> <span class="colorg">coupon</span> </h1>
      <% else %>
        <h1 class="text-center bottom"><%= t('orders.present') %><span class="colorg">coupon</span><%= t('orders.benefit') %></h1>
      <% end %>
      <div class="col-md-6 col-md-offset-3" style="border: dashed 2px whitesmoke;">
      <div class="text-center top bottom">
      <%= image_tag @order.promotion.shop.user.facebook_picture_url, { :class=>"avatar-large" }%>
      <p><strong><%= @order.promotion.shop.name_of_the_store  %> - <%= @order.promotion.shop.category %></strong> </p>
      <p><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i> <%= @order.promotion.shop.full_address  %> </p>

      <div class="image-container top bottom"><%= image_tag @order.promotion.photo_url, { :class=>"img-responsive" }%>
      <% if @order.status == "Booked" %>
      <div class="resume">
      <% else %>
      <div class="resumed">
      <% end %>
      <p> <%= @order.promotion.description %> </p>
      <p><%= t('orders.quantity') %>: <%= @order.quantity_ordered %> <%= @order.promotion.unit %></p>
      <p><%= t('orders.price') %>: <%= (@order.promotion.price_after_promotion_per_unit * @order.quantity_ordered).round(2) %> €</p>
      </div>
      </div>

      <% if @order.status == "Booked" %>
      <div class="text-center top">
        <%= simple_form_for :confirm, :url => confirm_order_path, :method => :post  do |f| %>
        <%= f.error_notification %>
        <%= f.input :code, label: "#{t('orders.enter-code')} #{@order.promotion.shop.name_of_the_store}"%>
        <%= f.button :submit,  t('orders.generate'), { :class=>"btn-medium fa fa-arrow-right top bottom" }  %>
        <div id="map" class="top" style="width: 100%; height: 600px;">

        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function() {
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
            });
          <% end %>
        <% end %>

        </div>
      <% end %>
      <% end %>
      </div>
</div>
</div>
</div>
</div>

<style type="text/css">
  footer,footer * {
display: none!important;
}
</style>